# Generated by Django 3.0.6 on 2020-05-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
                ('designer', models.CharField(max_length=40, null=True)),
                ('ratings', models.CharField(max_length=40, null=True)),
                ('quantity', models.CharField(max_length=40, null=True)),
                ('price', models.CharField(max_length=40, null=True)),
                ('description', models.CharField(max_length=250, null=True)),
                ('category', models.CharField(max_length=40, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
