# Generated by Django 3.0.6 on 2020-05-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_magmt', '0002_auto_20200530_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('mens', 'mens'), ('womens', 'womens'), ('kids', 'kids')], max_length=40, null=True),
        ),
    ]
