# Generated by Django 3.0.6 on 2020-05-30 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand_magmt', '0003_auto_20200530_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='brand_magmt.Registerpage'),
        ),
    ]
