# Generated by Django 3.0.6 on 2020-05-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_magmt', '0004_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerpage',
            name='certificate',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
