# Generated by Django 3.0.6 on 2020-06-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_magmt', '0006_auto_20200531_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('pics', models.FileField(upload_to='')),
                ('facebook', models.URLField(blank=True, max_length=100, null=True)),
                ('insta', models.URLField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
