# Generated by Django 3.0.6 on 2020-06-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_magmt', '0008_auto_20200601_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designer',
            name='pics',
        ),
        migrations.AddField(
            model_name='designer',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
