# Generated by Django 3.0.6 on 2020-06-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_magmt', '0009_auto_20200601_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
