# Generated by Django 3.0.7 on 2020-06-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_magmt', '0010_product_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='challenges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=30)),
                ('cdesc', models.TextField()),
                ('cparticipants', models.IntegerField()),
                ('cdesigners', models.IntegerField()),
                ('cdobegin', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('mens', 'mens'), ('womens', 'womens'), ('kids-boys', 'kids-boys'), ('kids-girls', 'kids-girls')], max_length=40, null=True),
        ),
    ]
